<?php

namespace MerchantBundle\Repository;

/**
 * CustomerSearchCriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerSearchCriteriaRepository extends \Doctrine\ORM\EntityRepository
{
}
