merchant:
    resource: "@MerchantBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

customer:
    resource: "@CustomerBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
langing_page:
    path: /customer
    defaults: { _controller: 'CustomerBundle\Controller\AccountController::customerLandingAction' }    
index_page:
    path: /customer/index
    defaults: { _controller: 'CustomerBundle\Controller\AccountController::customerIndexAction' }
    
customer_registration:
    path: /customer/registration
    defaults: { _controller: 'CustomerBundle\Controller\AccountController::customerRegistrationAction' }
    
merchant_login:
    path: /merchant/login
    defaults: { _controller: 'MerchantBundle\Controller\SecurityController::merchantLoginAction' }
       
login:
   path: /login
   defaults: { _controller: 'CustomerBundle\Controller\SecurityController::loginAction' }
   
logout:
   path: /logout
   defaults: { _controller: 'CustomerBundle\Controller\SecurityController::logoutAction' }   


       