<?php

namespace  Common\Model\Repository;
/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAddress(){
        $query = $this->createQueryBuilder('a')
        ->select('a');
        $query = $query->getQuery()->useQueryCache(true);
        return $query->getResult();
    }
}
