<?php

namespace Common\Model\Repository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends \Doctrine\ORM\EntityRepository
{
    public function brandNameList() {
        
        $productinfo = $this->getEntityManager()
        ->createQuery('SELECT b.brandName FROM Model:Brand b')
        ->getResult();
        return $productinfo;
    }
}
