<?php

namespace Common\Model\Repository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{ 
    public function findAllData(){
    $query = $this->createQueryBuilder('c')
    ->select('c');
    $query = $query->getQuery()->useQueryCache(true);
    return $query->getResult();
   }
   public function findCartListId($cid){
       
       $em = $this->getEntityManager();
       
       $qb = $em->createQueryBuilder();
       $qb->select('cl.id')
       ->from('Common\Model\CartList','cl')
       ->join('cl.cartId','c')
       ->where('c.customerId= ?1')
       ->setParameter(1,(int)$cid);
       $query=$qb->getQuery(); 
       $result=$query->getResult();
      // dump($result);die;
       return $result;
       
   }

}
