<?php

namespace Common\Model\Repository;

/**
 * CartListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartListRepository extends \Doctrine\ORM\EntityRepository
{
    //Retrive entire data of the entity from the DB
    public function findAllData(){
        $query = $this->createQueryBuilder('cl')
        ->select('cl');
        $query = $query->getQuery()->useQueryCache(true);
        return $query->getResult();
    }
    
    //To find the cartlist Id of a particular cart inorder to set it for another entity
    public function findCartListId($id){
       
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('cl.id')
        ->from('Common\Model\CartList','cl')
        ->where('cl.cartId= :id')
        ->setParameter('id',(int)$id);
        $query=$qb->getQuery();
        $result=$query->getResult();
      
        return $result;
        
    }
}
