<?php

namespace MerchantBundle\Repository;

/**
 * CartListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartListRepository extends \Doctrine\ORM\EntityRepository
{
}
