<?php

namespace Common\Model\Repository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{ 
    public function findAllData(){
    $query = $this->createQueryBuilder('c')
    ->select('c');
    $query = $query->getQuery()->useQueryCache(true);
    return $query->getResult();
   }
   
  
   
}
