<?php

namespace Common\Model\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function Categoryinfo($id) {
        
        $productinfo = $this->getEntityManager()
        ->createQuery('SELECT c FROM Model:Category c WHERE c.id= :cid')
        ->setParameter('cid', $id)
        ->getResult();
        return $productinfo;
    }
    public function categoryNameList() {
        
        $productinfo = $this->getEntityManager()
        ->createQuery('SELECT c.categoryName FROM Model:Category c')
        ->getResult();
        return $productinfo;
    }
}
