<?php

namespace Common\Model\Repository;

/**
 * Customer_planRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Customer_planRepository extends \Doctrine\ORM\EntityRepository
{
}
