<?php

namespace Common\Model\Repository;

/**
 * email_templateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class email_templateRepository extends \Doctrine\ORM\EntityRepository
{
}
