<?php

namespace Common\Model\Repository;

/**
 * MerchantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MerchantRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllDetails($id){
       
        $em = $this->getEntityManager();      
        $qb = $em->createQueryBuilder();
        $qb->select('count(p.productId) as productCount','p.productIMEI,d.productName')
        ->from('Common\Model\Product_Detail_List', 'p')
        ->join('p.productId','d')
        ->where('p.merchantId = ?1')
        ->setParameter(1,(int)$id);
        $query=$qb->getQuery();
      //  dump($query);die;
        $result=$query->getResult();
       // dump($result);die;
        return $result;
               
//     $query = "SELECT * FROM bestelling";
    
//     $result = mysql_query($query) or die(mysql_error());
    
//     while($row = mysql_fetch_array($result)){
//         $name = $row['name'];
//         $age = $row['age'];
    }
}
