<?php

namespace Common\Model\Repository;

/**
 * Product_Detail_ListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_Detail_ListRepository extends \Doctrine\ORM\EntityRepository
{
}
