<?php

namespace Common\Model\Repository;

/**
 * ProductOrderDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductOrderDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
