<?php

namespace Common\Model\Repository;

/**
 * ProductOrderDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductOrderDetailRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function productOrder(){
        $query = $this->createQueryBuilder('pod')
        ->select('pod', 'po', 'cl')
        ->leftJoin('pod.cartListId', 'cl')
        ->leftJoin('pod.productOrderId', 'po');
        $query = $query->getQuery()->useQueryCache(true);
        return $query->getResult();
    }
}
