<?php

namespace Common\Model\Repository;

/**
 * Product_DescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_DescriptionRepository extends \Doctrine\ORM\EntityRepository
{
   
}
