<?php

namespace Common\Model\Repository;

/**
 * Product_PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_PhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
