<?php

namespace Common\Model\Repository;

/**
 * SecretQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecretQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
