<?php

namespace  Common\Model\Repository;


/**
 * SecretAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecretAnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAnswerForAQuestion($questionId,$customerId) {
        $answer = $this->getEntityManager()
         ->createQuery(
             'SELECT s FROM Model:SecretAnswer s where s.customerId=:cid and s.questionId= :qid')
             ->setParameter('cid', $customerId)
             ->setParameter('qid', $questionId)
             ->getResult();          
        return $answer; 
       
       
    }
    
}
