<?php

namespace Common\Model\Repository;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function stateListForCountry($country){
        $query = $this->createQueryBuilder('s')
        ->select('s')
        ->leftJoin('s.countryId', 'c')
        ->andWhere('c.Id =:country')
        ->setParameter('country', $country);
        $query = $query->getQuery()->useQueryCache(true);
        return $query->getResult();
    }
}
