<?php

namespace Common\Model\Repository;

/**
 * WishListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishListRepository extends \Doctrine\ORM\EntityRepository
{
    
  
}
